---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "custom"
    directory: "/new-files/my_test.yml"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
  # - package-ecosystem: bundler
  #   directory: "/ruby"
  #   schedule:
  #     interval: "weekly"
